# Indentation does matter. Use the same amount of spaces ;) just use copy paste ;)
games:
 - name: QuakeLive
   demoFolder: c:/Documents and Settings/Dule/Application Data/id Software/quakelive/home/baseq3/demos/
   screenShotFolder: c:/Documents and Settings/Dule/Application Data/id Software/quakelive/home/baseq3/screenshots/
   outputFolder: d:/dev/DemoCollector/output/
   gameDemoExt: dm_73

 - name: Quake34
   demoFolder: c:/Quake5/cpma/demos/
   screenShotFolder: c:/Quake5/cpma/screenshots/
   outputFolder: d:/dev/DemoCollector/output/quake5
   gameDemoExt: dm_1337
